services:
  frontend:
    container_name: fullstack-reference-project_frontend
    image: fullstack-reference-project_frontend:latest
    build:
      context: ./frontend/
      dockerfile: ./Dockerfile
      target: base
    volumes:
      - ./frontend/http:/http
      - ./frontend/nextjs:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    container_name: fullstack-reference-project_backend
    image: fullstack-reference-project_backend:latest
    build:
      context: ./backend/
      dockerfile: ./Dockerfile
      target: base
    volumes:
      - ./backend/http:/http
    ports:
      - "8080:8080"


  db: 
    container_name: ourbnb_db
    image: postgres:18.1
    volumes:
      ./db/data:/var/lib/postgresql/
      ./db/init/:/docker-entrypoint-initdb.d

    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_NAME}    

  

